#############################################################################
# Makefile for building: SMBX\ NPC\ Editor.app/Contents/MacOS/SMBX\ NPC\ Editor
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mon Aug 24 17:05:49 2015
# Project:  npc.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.8/mkspecs/macx-g++ CONFIG+=x86_64 -o Makefile npc.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.8/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/usr/include -I. -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		customspinner.cpp \
		new_npc.cpp \
		customcheckbox.cpp \
		scorecombobox.cpp moc_mainwindow.cpp \
		moc_customspinner.cpp \
		moc_customcheckbox.cpp \
		moc_scorecombobox.cpp
OBJECTS       = main.o \
		mainwindow.o \
		customspinner.o \
		new_npc.o \
		customcheckbox.o \
		scorecombobox.o \
		moc_mainwindow.o \
		moc_customspinner.o \
		moc_customcheckbox.o \
		moc_scorecombobox.o
DIST          = /usr/local/Qt4.8/mkspecs/common/unix.conf \
		/usr/local/Qt4.8/mkspecs/common/mac.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-base.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-macx.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.8/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.8/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.8/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.8/mkspecs/features/debug.prf \
		/usr/local/Qt4.8/mkspecs/features/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.8/mkspecs/features/shared.prf \
		/usr/local/Qt4.8/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.8/mkspecs/features/qt.prf \
		/usr/local/Qt4.8/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.8/mkspecs/features/moc.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.8/mkspecs/features/resources.prf \
		/usr/local/Qt4.8/mkspecs/features/uic.prf \
		/usr/local/Qt4.8/mkspecs/features/yacc.prf \
		/usr/local/Qt4.8/mkspecs/features/lex.prf \
		/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf \
		npc.pro
QMAKE_TARGET  = SMBX\ NPC\ Editor
DESTDIR       = 
TARGET        = SMBX\ NPC\ Editor.app/Contents/MacOS/SMBX\ NPC\ Editor

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile SMBX\ NPC\ Editor.app/Contents/PkgInfo SMBX\ NPC\ Editor.app/Contents/Resources/empty.lproj SMBX\ NPC\ Editor.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h ui_customspinner.h ui_customcheckbox.h ui_scorecombobox.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) SMBX\ NPC\ Editor.app/Contents/MacOS/ || $(MKDIR) SMBX\ NPC\ Editor.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: npc.pro  /usr/local/Qt4.8/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.8/mkspecs/common/unix.conf \
		/usr/local/Qt4.8/mkspecs/common/mac.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-base.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-macx.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.8/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.8/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.8/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.8/mkspecs/features/debug.prf \
		/usr/local/Qt4.8/mkspecs/features/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.8/mkspecs/features/shared.prf \
		/usr/local/Qt4.8/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.8/mkspecs/features/qt.prf \
		/usr/local/Qt4.8/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.8/mkspecs/features/moc.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.8/mkspecs/features/resources.prf \
		/usr/local/Qt4.8/mkspecs/features/uic.prf \
		/usr/local/Qt4.8/mkspecs/features/yacc.prf \
		/usr/local/Qt4.8/mkspecs/features/lex.prf \
		/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Qt4.8/mkspecs/macx-g++ CONFIG+=x86_64 -o Makefile npc.pro
/usr/local/Qt4.8/mkspecs/common/unix.conf:
/usr/local/Qt4.8/mkspecs/common/mac.conf:
/usr/local/Qt4.8/mkspecs/common/gcc-base.conf:
/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf:
/usr/local/Qt4.8/mkspecs/common/g++-base.conf:
/usr/local/Qt4.8/mkspecs/common/g++-macx.conf:
/usr/local/Qt4.8/mkspecs/qconfig.pri:
/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Qt4.8/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.8/mkspecs/features/qt_config.prf:
/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.8/mkspecs/features/default_pre.prf:
/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.8/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.8/mkspecs/features/debug.prf:
/usr/local/Qt4.8/mkspecs/features/default_post.prf:
/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf:
/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.8/mkspecs/features/shared.prf:
/usr/local/Qt4.8/mkspecs/features/warn_on.prf:
/usr/local/Qt4.8/mkspecs/features/qt.prf:
/usr/local/Qt4.8/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.8/mkspecs/features/moc.prf:
/usr/local/Qt4.8/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.8/mkspecs/features/resources.prf:
/usr/local/Qt4.8/mkspecs/features/uic.prf:
/usr/local/Qt4.8/mkspecs/features/yacc.prf:
/usr/local/Qt4.8/mkspecs/features/lex.prf:
/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.8/mkspecs/macx-g++ CONFIG+=x86_64 -o Makefile npc.pro

SMBX\ NPC\ Editor.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) SMBX\ NPC\ Editor.app/Contents || $(MKDIR) SMBX\ NPC\ Editor.app/Contents 
	@$(DEL_FILE) SMBX\ NPC\ Editor.app/Contents/PkgInfo
	@echo "APPL????" >SMBX\ NPC\ Editor.app/Contents/PkgInfo
SMBX\ NPC\ Editor.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) SMBX\ NPC\ Editor.app/Contents/Resources || $(MKDIR) SMBX\ NPC\ Editor.app/Contents/Resources 
	@touch SMBX\ NPC\ Editor.app/Contents/Resources/empty.lproj
	
SMBX\ NPC\ Editor.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) SMBX\ NPC\ Editor.app/Contents || $(MKDIR) SMBX\ NPC\ Editor.app/Contents 
	@$(DEL_FILE) SMBX\ NPC\ Editor.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,SMBX\ NPC\ Editor,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.8/mkspecs/macx-g++/Info.plist.app >SMBX\ NPC\ Editor.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/SMBX\ NPC\ Editor1.0.0 || $(MKDIR) .tmp/SMBX\ NPC\ Editor1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SMBX\ NPC\ Editor1.0.0/ && $(COPY_FILE) --parents mainwindow.h customspinner.h new_npc.h customcheckbox.h scorecombobox.h .tmp/SMBX\ NPC\ Editor1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp customspinner.cpp new_npc.cpp customcheckbox.cpp scorecombobox.cpp .tmp/SMBX\ NPC\ Editor1.0.0/ && $(COPY_FILE) --parents mainwindow.ui customspinner.ui customcheckbox.ui scorecombobox.ui .tmp/SMBX\ NPC\ Editor1.0.0/ && (cd `dirname .tmp/SMBX\ NPC\ Editor1.0.0` && $(TAR) SMBX\ NPC\ Editor1.0.0.tar SMBX\ NPC\ Editor1.0.0 && $(COMPRESS) SMBX\ NPC\ Editor1.0.0.tar) && $(MOVE) `dirname .tmp/SMBX\ NPC\ Editor1.0.0`/SMBX\ NPC\ Editor1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SMBX\ NPC\ Editor1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r SMBX\ NPC\ Editor.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_customspinner.cpp moc_customcheckbox.cpp moc_scorecombobox.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_customspinner.cpp moc_customcheckbox.cpp moc_scorecombobox.cpp
moc_mainwindow.cpp: mainwindow.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

moc_customspinner.cpp: customspinner.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ customspinner.h -o moc_customspinner.cpp

moc_customcheckbox.cpp: customcheckbox.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ customcheckbox.h -o moc_customcheckbox.cpp

moc_scorecombobox.cpp: scorecombobox.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ scorecombobox.h -o moc_scorecombobox.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_customspinner.h ui_customcheckbox.h ui_scorecombobox.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_customspinner.h ui_customcheckbox.h ui_scorecombobox.h
ui_mainwindow.h: mainwindow.ui \
		customspinner.h \
		customcheckbox.h
	/Developer/Tools/Qt/uic mainwindow.ui -o ui_mainwindow.h

ui_customspinner.h: customspinner.ui
	/Developer/Tools/Qt/uic customspinner.ui -o ui_customspinner.h

ui_customcheckbox.h: customcheckbox.ui
	/Developer/Tools/Qt/uic customcheckbox.ui -o ui_customcheckbox.h

ui_scorecombobox.h: scorecombobox.ui
	/Developer/Tools/Qt/uic scorecombobox.ui -o ui_scorecombobox.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		customcheckbox.h \
		customspinner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

customspinner.o: customspinner.cpp customspinner.h \
		ui_customspinner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o customspinner.o customspinner.cpp

new_npc.o: new_npc.cpp new_npc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o new_npc.o new_npc.cpp

customcheckbox.o: customcheckbox.cpp customcheckbox.h \
		ui_customcheckbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o customcheckbox.o customcheckbox.cpp

scorecombobox.o: scorecombobox.cpp scorecombobox.h \
		ui_scorecombobox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scorecombobox.o scorecombobox.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_customspinner.o: moc_customspinner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_customspinner.o moc_customspinner.cpp

moc_customcheckbox.o: moc_customcheckbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_customcheckbox.o moc_customcheckbox.cpp

moc_scorecombobox.o: moc_scorecombobox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scorecombobox.o moc_scorecombobox.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

